# Generated by Django 4.1.1 on 2022-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_pw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpw',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
